---
title: "Nate"
author: "Nathan Gendich"
date: "11/30/2020"
output: html_document
---



```{r}
# Read the data set



```


```{r}
fulldata$gender <-ifelse(fulldata$gender >1, "Female",
                         ifelse(fulldata$gender > 0, "Male",
                                "Unknown"))
fulldata$age <- 2019 - fulldata$birth.year

```

```{r}
library(dplyr)
library(ggplot2)
by_day <- group_by(fulldata, date)
ridesperday <- summarise(by_day,
                         count = n())
                        
ridesperday$rides <- ridesperday$count
ridesperday$count <- NULL
ridesperday
tempperday <- summarise(by_day, TAVG, PRCP, AWND, SNOW, SNWD)
perday <- merge(ridesperday,tempperday, by.x = "date", by.y = "date")
perday<-unique(perday)
perday$TEMP <- ifelse(perday$TAVG >= 80, "Hot",
                               ifelse(perday$TAVG >= 60, "Warm",
                                      ifelse(perday$TAVG >= 45, "Temperate",
                                             ifelse(perday$TAVG >= 33, "Chilly",
                                                  ifelse(perday$TAVG >= 0, "Freezing")))))
perday$Rainfall <- ifelse(perday$PRCP > 0.5, "Heavy",
                          ifelse(perday$PRCP >0.1, "Moderate",
                                 ifelse(perday$PRCP > 0, "Light", "None")))
perday[is.na(perday)] = 0
perday$Wind <- ifelse(perday$AWND > 7.5, "Gentle Breeze",
                          ifelse(perday$AWND >3.5, "Light Breeze",
                                 ifelse(perday$AWND > 1, "Light Air", "None")))
                                       
perday
```

`r mean(perday$rides)`
`r sd(perday$rides)`


```{r}
#Use perday to find avg daily rides given perday TEMP, Rainfall, Wind
by_temp <- group_by(perday, TEMP)
daystemp <- summarise(by_temp,
                         count = n(),
                         rides_avg = round(mean(rides, na.rm = TRUE),0))
daystemp

by_rain <- group_by(perday, Rainfall)
daysrain <- summarise(by_rain,
                         count = n(),
                         rides_avg = round(mean(rides, na.rm = TRUE),0))
daysrain

by_wind <- group_by(perday, Wind)
dayswind <- summarise(by_wind,
                         count = n(),
                         rides_avg = round(mean(rides, na.rm = TRUE),0))
dayswind
```

```{r}
# grid.arrange
library(grid)
library(gridExtra)
ggplot(perday, aes(x=date)) +
  geom_line( aes(y=rides))

ggplot(perday, aes(x=date, y=TAVG))+ 
  geom_line()
```








